# Generated by Django 5.0.2 on 2024-02-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
